version: '3.4'

services:
  authdb:
    image: mcr.microsoft.com/mssql/server:2017-latest
  chatdb:
    image: mongodb/mongodb-community-server:6.0-ubuntu2204
  unoschat.conversationapi:
    image: ${DOCKER_REGISTRY-}unoschatconversationapi
    build:
      context: .
      dockerfile: UNOSChat.ConversationAPI/Dockerfile
  unoschat.authenticationapi:
    image: ${DOCKER_REGISTRY-}unoschatauthenticationapi
    build:
      context: .
      dockerfile: UNOSChat.AuthenticationAPI/Dockerfile
  unoschat.client:
    image: ${DOCKER_REGISTRY-}unoschatclient
    build:
      context: .
      dockerfile: unoschat.client/Dockerfile
  ocelotgateway:
    image: ${DOCKER_REGISTRY-}ocelotgateway
    build:
      context: .
      dockerfile: OcelotGateway/Dockerfile
volumes:
  mongo_data:
